### me.jpg

GET https://mwojcik.azurewebsites.net/content/images/2018/10/me.jpg

### Header-1.jpg
GET https://mwojcik.azurewebsites.net/content/images/2019/01/Header-1.jpg

### favicon.ico
GET https://mwojcik.azurewebsites.net/favicon.ico

### Introduction-to-Markov-Chains-in-F----vimeo.png
GET https://mwojcik.azurewebsites.net/content/images/2019/05/Introduction-to-Markov-Chains-in-F----vimeo.png

### A-Simple-Bid-Recommendation-Engine-Using-FParsec-and-CodeDom---vimeo.png
GET  https://mwojcik.azurewebsites.net/content/images/2019/05/A-Simple-Bid-Recommendation-Engine-Using-FParsec-and-CodeDom---vimeo.png

### Buffer6.net.png
GET https://mwojcik.azurewebsites.net/content/images/2019/07/Buffer6.net.png

###
GET https://mwojcik.azurewebsites.net/Images/Visual-Studio-Debugger-Tips-and-Tricks-step-out/recursive-function1.png